//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Частный_детектив
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Oplata { get; set; }
        public int ClientId { get; set; }
        public string id_Client { get; set; }
        public string id_Spektak { get; set; }
    }
}
