//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Частный_детектив
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spektak
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
        public string Actors { get; set; }
        public int Photo { get; set; }
        public string Actual { get; set; }
        public int PostanovId { get; set; }
    
        public virtual Postanov Postanov { get; set; }
    }
}
